server:
  port: 8084

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-final-v1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.Map
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

notification:
  webhook:
    url: https://webhook.site/fcf22543-a134-4452-9d80-50c5373d7bf0
  email:
    from: payments@paymentengine.com
    to: customer@example.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  prometheus:
    metrics:
      export:
        enabled: true

